name: CI

on:
  push:
    branches: [ "release/*" ]
  pull_request:
    branches: [ "release/*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:          
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}        
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: oyxbh/cicdtest:V1.0
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}  
    - name: Send a Message 
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: ${{ secrets.Ning Shen }} \n Matriculation numbers: ${{ secrets.A0265808U }} \n Email: ${{ secrets.e1068716@u.nus.edu }} \n Repo: ${{ github.git://github.com/OYXBH324/workshop.git }} \n Image Name: ${{ secrets.OYXBH }}  \n Image url: ${{ secrets.https://hub.docker.com/repository/docker/oyxbh/cicdtest }}"
                  }
                }
              ]
            }
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.https://hooks.slack.com/services/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  }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
